DROP TABLE IF EXISTS TBL_TRAININGS;
CREATE TABLE IF NOT EXISTS TBL_TRAININGS
(
    ID              CHAR(36)                 NOT NULL PRIMARY KEY,
    TOPIC           VARCHAR(255)             NOT NULL,
    LOCATION        VARCHAR(255)             NOT NULL CHECK (LOCATION IN ('Remote', 'On-Site') ),
    INSTRUCTOR      VARCHAR(255)             NOT NULL,
    START_TIME      TIMESTAMP WITH TIME ZONE NOT NULL,
    AVAILABLE_SEATS SMALLINT                 NOT NULL DEFAULT 7
);
